{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Ques.5 Predict the sentiment of tweets by followers of naveen_odisha"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:elasticsearch:POST http://localhost:9200/sentiment/test-type [status:N/A request:2.066s]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\elasticsearch\\connection\\http_urllib3.py\", line 91, in perform_request\n",
      "    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 608, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\util\\retry.py\", line 224, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 558, in urlopen\n",
      "    body=body, headers=headers)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 353, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1057, in request\n",
      "    self._send_request(method, url, body, headers)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1097, in _send_request\n",
      "    self.endheaders(body)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1053, in endheaders\n",
      "    self._send_output(message_body)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 897, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 859, in send\n",
      "    self.connect()\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connection.py\", line 162, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connection.py\", line 146, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000000001D517B00>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it\n",
      "WARNING:elasticsearch:POST http://localhost:9200/sentiment/test-type [status:N/A request:2.072s]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\elasticsearch\\connection\\http_urllib3.py\", line 91, in perform_request\n",
      "    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 608, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\util\\retry.py\", line 224, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 558, in urlopen\n",
      "    body=body, headers=headers)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 353, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1057, in request\n",
      "    self._send_request(method, url, body, headers)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1097, in _send_request\n",
      "    self.endheaders(body)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1053, in endheaders\n",
      "    self._send_output(message_body)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 897, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 859, in send\n",
      "    self.connect()\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connection.py\", line 162, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connection.py\", line 146, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000000001D517A90>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it\n",
      "WARNING:elasticsearch:POST http://localhost:9200/sentiment/test-type [status:N/A request:2.036s]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\elasticsearch\\connection\\http_urllib3.py\", line 91, in perform_request\n",
      "    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 608, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\util\\retry.py\", line 224, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 558, in urlopen\n",
      "    body=body, headers=headers)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 353, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1057, in request\n",
      "    self._send_request(method, url, body, headers)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1097, in _send_request\n",
      "    self.endheaders(body)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1053, in endheaders\n",
      "    self._send_output(message_body)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 897, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 859, in send\n",
      "    self.connect()\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connection.py\", line 162, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connection.py\", line 146, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000000001D517B70>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it\n",
      "WARNING:elasticsearch:POST http://localhost:9200/sentiment/test-type [status:N/A request:2.049s]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\elasticsearch\\connection\\http_urllib3.py\", line 91, in perform_request\n",
      "    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 608, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\util\\retry.py\", line 224, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 558, in urlopen\n",
      "    body=body, headers=headers)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connectionpool.py\", line 353, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1057, in request\n",
      "    self._send_request(method, url, body, headers)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1097, in _send_request\n",
      "    self.endheaders(body)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 1053, in endheaders\n",
      "    self._send_output(message_body)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 897, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\httplib.py\", line 859, in send\n",
      "    self.connect()\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connection.py\", line 162, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\Users\\test\\Anaconda2\\lib\\site-packages\\urllib3\\connection.py\", line 146, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000000001D517BA8>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.0\n",
      "neutral\n"
     ]
    },
    {
     "ename": "ConnectionError",
     "evalue": "ConnectionError(<urllib3.connection.HTTPConnection object at 0x000000001D517BA8>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x000000001D517BA8>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mConnectionError\u001b[0m                           Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-17-cdb356e11887>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     71\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     72\u001b[0m     \u001b[1;31m# search twitter for \"congress\" keyword\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 73\u001b[1;33m     \u001b[0mstream\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfilter\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtrack\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'naveen_odisha'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mC:\\Users\\test\\Anaconda2\\lib\\site-packages\\tweepy\\streaming.pyc\u001b[0m in \u001b[0;36mfilter\u001b[1;34m(self, follow, track, async, locations, stall_warnings, languages, encoding, filter_level)\u001b[0m\n\u001b[0;32m    443\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msession\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mparams\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m{\u001b[0m\u001b[1;34m'delimited'\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;34m'length'\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    444\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mhost\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m'stream.twitter.com'\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 445\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_start\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0masync\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    446\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    447\u001b[0m     def sitestream(self, follow, stall_warnings=False,\n",
      "\u001b[1;32mC:\\Users\\test\\Anaconda2\\lib\\site-packages\\tweepy\\streaming.pyc\u001b[0m in \u001b[0;36m_start\u001b[1;34m(self, async)\u001b[0m\n\u001b[0;32m    359\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_thread\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstart\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    360\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 361\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_run\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    362\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    363\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mon_closed\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mresp\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Users\\test\\Anaconda2\\lib\\site-packages\\tweepy\\streaming.pyc\u001b[0m in \u001b[0;36m_run\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    292\u001b[0m             \u001b[1;31m# call a handler first so that the exception can be logged.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    293\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mlistener\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mon_exception\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mexception\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 294\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mexception\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    295\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    296\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_data\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdata\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mConnectionError\u001b[0m: ConnectionError(<urllib3.connection.HTTPConnection object at 0x000000001D517BA8>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x000000001D517BA8>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it)"
     ]
    }
   ],
   "source": [
    "import json\n",
    "from tweepy.streaming import StreamListener\n",
    "from tweepy import OAuthHandler\n",
    "from tweepy import Stream\n",
    "from textblob import TextBlob\n",
    "from elasticsearch import Elasticsearch\n",
    "\n",
    "# import twitter keys and tokens\n",
    "from config import *\n",
    "\n",
    "# create instance of elasticsearch\n",
    "es = Elasticsearch()\n",
    "\n",
    "TWITTER_CONSUMER_KEY = 'CONSUMER KEY'\n",
    "TWITTER_CONSUMER_SECRET = 'CONSUMER SECRET'\n",
    "TWITTER_ACCESS_TOKEN = 'ACCESS TOKEN'\n",
    "TWITTER_ACCESS_TOKEN_SECRET = 'ACCESS TOKEN SECRET'\n",
    "\n",
    "\n",
    "class TweetStreamListener(StreamListener):\n",
    "\n",
    "    # on success\n",
    "    def on_data(self, data):\n",
    "\n",
    "        # decode json\n",
    "        dict_data = json.loads(data)\n",
    "\n",
    "        # pass tweet into TextBlob\n",
    "        tweet = TextBlob(dict_data[\"text\"])\n",
    "\n",
    "        # output sentiment polarity\n",
    "        print tweet.sentiment.polarity\n",
    "\n",
    "        # determine if sentiment is positive, negative, or neutral\n",
    "        if tweet.sentiment.polarity < 0:\n",
    "            sentiment = \"negative\"\n",
    "        elif tweet.sentiment.polarity == 0:\n",
    "            sentiment = \"neutral\"\n",
    "        else:\n",
    "            sentiment = \"positive\"\n",
    "\n",
    "        # output sentiment\n",
    "        print sentiment\n",
    "\n",
    "        # add text and sentiment info to elasticsearch\n",
    "        es.index(index=\"sentiment\",\n",
    "                 doc_type=\"test-type\",\n",
    "                 body={\"author\": dict_data[\"user\"][\"screen_name\"],\n",
    "                       \"date\": dict_data[\"created_at\"],\n",
    "                       \"message\": dict_data[\"text\"],\n",
    "                       \"polarity\": tweet.sentiment.polarity,\n",
    "                       \"subjectivity\": tweet.sentiment.subjectivity,\n",
    "                       \"sentiment\": sentiment})\n",
    "        return True\n",
    "\n",
    "    # on failure\n",
    "    def on_error(self, status):\n",
    "        print status\n",
    "\n",
    "if __name__ == '__main__':\n",
    "\n",
    "    # create instance of the tweepy tweet stream listener\n",
    "    listener = TweetStreamListener()\n",
    "\n",
    "    # set twitter keys/tokens\n",
    "    auth = OAuthHandler(TWITTER_CONSUMER_KEY,TWITTER_CONSUMER_SECRET)\n",
    "    auth.set_access_token(TWITTER_ACCESS_TOKEN,TWITTER_ACCESS_TOKEN_SECRET)\n",
    "\n",
    "    # create instance of the tweepy stream\n",
    "    stream = Stream(auth, listener)\n",
    "\n",
    "    # search twitter for \"congress\" keyword\n",
    "    stream.filter(track=['naveen_odisha'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
